name: benchapp
description: Simple Dart DB performance benchmark
version: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.0 <4.0.0'

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  path: ^1.9.0
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  isar: ^3.1.0+1
  isar_flutter_libs: any

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  objectbox_generator: any
  build_runner: any
  hive_generator: any
  isar_generator: any

#dependency_overrides:
#  objectbox:
#    path: ../objectbox-dart/objectbox
#  objectbox_flutter_libs:
#    path: ../objectbox-dart/flutter_libs
#  objectbox_generator:
#    path: ../objectbox-dart/generator
